spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mericmert/jobss-config.git
  security:
    user:
      password: ${CONFIG_SERVICE_PASSWORD}
  main:
    banner-mode: off

server:
  port: 8888
